version: '3.5'

services:

  frontend:
    image: '1_12_front'
    ports: 
      - 5000:5000
    container_name: frontend

  backend:
    image: '1_12_back_local'
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_HOST=database
    container_name: backend

  redis:
    image: 'redis'
    environment:
      - REDIS=localhost
    container_name: redis

  database:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    container_name: postgres_database

  nginx:
    image: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: nginx

