FROM ubuntu:16.04 as build-stage
WORKDIR /app

RUN apt-get update && apt-get install -y git && \
    git clone https://github.com/docker-hy/spring-example-project.git


FROM openjdk:8-alpine
COPY --from=build-stage /app/spring-example-project /app/usr
WORKDIR /app/usr

RUN chmod +x mvnw && ./mvnw package && \
    addgroup -S appgroup && adduser -S docker -G appgroup

USER docker
EXPOSE 8080

CMD ["/bin/sh", "-c", "java -jar ./target/docker-example-1.1.3.jar"]